env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-param-reassign: ["error", { "props": false }],
  no-plusplus: 0,
  no-undef: 0,
  no-restricted-syntax: 0,
  max-len: 0
}

